@startuml spoke
title Spoke Architecture
hide empty members

package "Messaging" <<cloud>> {
    circle " " as messaging
}

package factories {
    class TokenFactory
    class PoolEscrowFactory
    class PoolEscrow
}

class Spoke
class SpokeHandler
class SpokeRegistry

class BalanceSheet
class VaultRegistry
class ShareToken
interface ITransferHook
interface IRequestManager

Spoke -down-> SpokeRegistry
Spoke -up-> messaging

messaging --> SpokeHandler
messaging --> VaultRegistry
SpokeHandler --> SpokeRegistry
SpokeHandler --> TokenFactory
SpokeHandler --> PoolEscrowFactory

BalanceSheet --> SpokeRegistry
VaultRegistry --> SpokeRegistry

SpokeRegistry o-- "n" IRequestManager
SpokeRegistry o-- "n" ShareToken

' Factories
TokenFactory ..> "n" ShareToken
PoolEscrowFactory ..> "n" PoolEscrow
ShareToken o--> ITransferHook

@enduml
