@startuml
hide empty members

class JsonRegistry
class CommonDeployer
class HubDeployer
class SpokeDeployer
class FullDeployer

class Axelar
class Wormhole
class Localhost

CommonDeployer -up-|> JsonRegistry
HubDeployer -up-|> CommonDeployer
SpokeDeployer -up-|> CommonDeployer
FullDeployer -up-|> HubDeployer
FullDeployer -up-|> SpokeDeployer

Axelar -up-|> FullDeployer
Wormhole -up-|> FullDeployer
Localhost -up-|> FullDeployer

note right of SpokeDeployer: Used in CV ITs
note left of HubDeployer: Used in CP ITs
note right of FullDeployer: Used in CP-CV ITs
note bottom of Localhost: Used in Testnets
@enduml
