@startuml deployers
title Deployers
hide empty members

class JsonRegistry << (S, motivation) >>
class CreateXScript << (S, motivation) >>
class DeployGateScript << (S, motivation) >>
class GateProposalScript << (S, motivation) >>

class BaseDeployer << (S, motivation) >>
class GatedDeployer << (S, motivation) >>

class DeployAdapters << (S, application) >>

class FullDeployer  << (S, application) >> {
    + function deployFull()
}
class LaunchDeployer  << (S, application) >> {
    + function commit()
    + function revoke()
    + function deploy()
}

class CoreActionBatcher << (C, implementation) >>
class NonCoreActionBatcher << (C, implementation) >>
class AdapterActionBatcher << (C, implementation) >>

class DeployerInput << (S,strategy) JsonConfig >>

enum DeployPhase {
    Commit
    Deploy
}

BaseDeployer -up-|> JsonRegistry
BaseDeployer -up-|> CreateXScript
DeployGateScript -up-|> CreateXScript
GateProposalScript -up-|> DeployGateScript

GatedDeployer --up-|> BaseDeployer
GatedDeployer --up-|> GateProposalScript
FullDeployer -up-|> GatedDeployer
LaunchDeployer -up-|> FullDeployer

DeployAdapters ---up-|> BaseDeployer

GatedDeployer -right> DeployPhase
FullDeployer -left> DeployerInput

FullDeployer ...> CoreActionBatcher
FullDeployer ...> NonCoreActionBatcher
FullDeployer ...> AdapterActionBatcher

note right of JsonRegistry: Utilities to write in the env files
note left of DeployGateScript: From the create3-gate dependency
note right of BaseDeployer: Base utilities to use create3\n in the project
note right of GatedDeployer: Helpers to use DeployGate
note right of FullDeployer: Used in integration tests
note bottom of LaunchDeployer: Loads network config from JSON;\nentry point for production deployments

@enduml
