@startuml
hide empty members

package misc {
    abstract Multicall
    abstract ReentrancyProtection
    abstract Recoverable
}

package common {
    class MessageDispatcher
    class Gateway
}

class Holdings
class HubRegistry
class ShareClassManager
class Accounting
class Hub
class HubHelpers

interface ISnapshotHook
interface IValuation

Hub -up-|> Multicall
Multicall -up-|> ReentrancyProtection
Hub -up-|> Recoverable

Hub --> Holdings
Hub --> HubRegistry
Hub --> ShareClassManager
Hub --> Accounting
HubHelpers --> Holdings
HubHelpers --> HubRegistry
HubHelpers --> ShareClassManager
HubHelpers --> Accounting
Hub -up-> MessageDispatcher
HubHelpers -up-> MessageDispatcher
Hub -up-> Gateway
Holdings --> IValuation
Holdings --> ISnapshotHook

Holdings --> HubRegistry
ShareClassManager --> HubRegistry
Accounting --> HubRegistry

@enduml
