@startuml
left to right direction
collections Adapters <<common>>
collections HubManagers <<hub>> as "Managers"
collections SpokeManagers <<spoke>> as "Managers"
rectangle MessageProcessor <<common>>
rectangle MessageDispatcher <<common>>
rectangle Gateway <<common>>
rectangle MultiAdapter <<common>>

HubManagers <-left- MessageProcessor
HubManagers <-right-> MessageDispatcher

SpokeManagers <-- MessageProcessor
SpokeManagers <--> MessageDispatcher

MessageProcessor <-down- Gateway
MessageDispatcher -down-> Gateway

Gateway <-down-> MultiAdapter
MultiAdapter <-down-> Adapters

@enduml
