@startuml
hide empty members

package common {
    class Gateway
    class MessageDispatcher
}

package managers {
    class OnOfframpManager
    class MerkleProofManager
}

class Hidden

class Spoke
class Escrow
class PoolEscrow
class ShareToken
class BalanceSheet
class PoolEscrowFactory
class TokenFactory

interface IVaultFactory
interface IVault
interface IVaultManager

Spoke -up-> TokenFactory
Spoke -up-> PoolEscrowFactory
Spoke -up->"n" IVaultFactory
Spoke -->"n" ShareToken
Spoke -right->"n" IVault
Spoke --> Gateway
Spoke --> MessageDispatcher

BalanceSheet -up-> PoolEscrowFactory
BalanceSheet --> MessageDispatcher
BalanceSheet -right-> Spoke
BalanceSheet --> Gateway

PoolEscrowFactory .right.> PoolEscrow
PoolEscrow -up-|> Escrow

ShareToken -up-> IVault
IVault --> IVaultManager

OnOfframpManager -down-> BalanceSheet
MerkleProofManager -up-> BalanceSheet

TokenFactory ...> ShareToken
IVaultFactory ..> IVault

' Hidden stuff to make things more visual

hide Hidden

OnOfframpManager -down[hidden]-> MerkleProofManager
MerkleProofManager -down-> Hidden
Hidden -up-> BalanceSheet

@enduml
