@startuml
hide empty members

package common {
    class Gateway
    class MessageDispatcher
    class PoolEscrow
    class PoolEscrowFactory
}

package managers {
    class OnOfframpManager
    class MerkleProofManager
}

package hooks {
    class FreezeOnly
    class RedemptionRestrictions
    class FullRestrictions
}

class Hidden

class Spoke
class ShareToken
class BalanceSheet
class TokenFactory

interface IVaultFactory
interface IVault
interface IVaultManager
interface IRequestManager
interface ITransferHook

ITransferHook -up-> FreezeOnly
ITransferHook -up-> RedemptionRestrictions
ITransferHook -up-> FullRestrictions

Spoke -left-> TokenFactory
Spoke -down--> PoolEscrowFactory
Spoke -up->"n" IVaultFactory
Spoke -up->"n" ShareToken
Spoke -up->"n" IVault
Spoke ---> Gateway
Spoke ---> MessageDispatcher
Spoke -right->"n" IRequestManager

BalanceSheet -right-> PoolEscrowFactory
BalanceSheet -left--> Spoke
BalanceSheet --> MessageDispatcher
BalanceSheet --> Gateway

PoolEscrowFactory .right.> PoolEscrow

ShareToken -up-> ITransferHook
ShareToken -right-> IVault
IVault -up-> IVaultManager

OnOfframpManager -down-> BalanceSheet
MerkleProofManager -up-> BalanceSheet

TokenFactory .up.> ShareToken
IVaultFactory .left.> IVault

' Hidden stuff to make things more visual

hide Hidden

OnOfframpManager -down[hidden]-> MerkleProofManager
MerkleProofManager -down-> Hidden
Hidden -up-> BalanceSheet

@enduml
