// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import {CastLib} from "../../../misc/libraries/CastLib.sol";
import {MathLib} from "../../../misc/libraries/MathLib.sol";
import {BytesLib} from "../../../misc/libraries/BytesLib.sol";

import {PoolId} from "../../types/PoolId.sol";
import {AssetId} from "../../types/AssetId.sol";

enum MessageType {
    /// @dev Placeholder for null message type
    _Invalid,
    // --- Protocol-wide (pool-independent) ---
    // NOTE: everything below `NotifyPool` is treated as pool-dependent (carries its PoolId at offset 1);
    // see `messagePoolId` / `messageSourceCentrifugeId`. Keep pool-independent messages above `NotifyPool`.
    ScheduleUpgrade,
    CancelUpgrade,
    RegisterAsset,
    SetPoolAdapters,
    // --- Pool & share-class notifications ---
    NotifyPool,
    NotifyShareClass,
    NotifyPricePoolPerShare,
    NotifyPricePoolPerAsset,
    NotifyShareMetadata,
    // --- Share transfers ---
    InitiateTransferShares,
    ExecuteTransferShares,
    // --- Vaults & restrictions ---
    UpdateRestriction,
    UpdateVault,
    // --- Balance sheet ---
    UpdateAssets,
    UpdateShares,
    // --- Investment requests ---
    Request,
    RequestCallback,
    SetRequestManager,
    // --- Manager calls & authorization ---
    ManagerCallFromSpoke,
    ManagerCallFromHub,
    UpdateManager,
    SetPolicy,
    AuthorizeSpokeCall,
    UnauthorizeSpokeCall
}

/// @dev Used internally in the UpdateVault message (not represent a submessage)
enum VaultUpdateKind {
    DeployAndLink,
    Link,
    Unlink
}

/// @dev Used internally in the UpdateManager message to select which contract's manager is updated.
enum ManagerKind {
    Adapter,
    Gateway,
    Spoke,
    Bridger
}

library MessageLib {
    using MessageLib for bytes;
    using BytesLib for bytes;
    using CastLib for *;
    using MathLib for *;

    error UnknownMessageType();
    error InvalidPoolHome();
    error InvalidAssetHome();

    uint16 internal constant MAINNET_CENTRIFUGE_ID = 1;

    /// @dev Encode all message lengths in this constant to avoid a large list of if/elseif checks
    /// and reduce generated bytecode.
    /// If the message has some dynamic part, will be added later in `messageLength()`.
    // forgefmt: disable-next-item
    uint256 constant MESSAGE_LENGTHS_1 =
        (33  << uint8(MessageType.ScheduleUpgrade) * 8) +
        (33  << uint8(MessageType.CancelUpgrade) * 8) +
        (18  << uint8(MessageType.RegisterAsset) * 8) +
        (14  << uint8(MessageType.SetPoolAdapters) * 8) +
        (9   << uint8(MessageType.NotifyPool) * 8) +
        (250 << uint8(MessageType.NotifyShareClass) * 8) +
        (49  << uint8(MessageType.NotifyPricePoolPerShare) * 8) +
        (65  << uint8(MessageType.NotifyPricePoolPerAsset) * 8) +
        (185 << uint8(MessageType.NotifyShareMetadata) * 8) +
        (139  << uint8(MessageType.InitiateTransferShares) * 8) +
        (89  << uint8(MessageType.ExecuteTransferShares) * 8) +
        (41  << uint8(MessageType.UpdateRestriction) * 8) +
        (90  << uint8(MessageType.UpdateVault) * 8) +
        (91  << uint8(MessageType.UpdateAssets) * 8) +
        (75  << uint8(MessageType.UpdateShares) * 8) +
        (57  << uint8(MessageType.Request) * 8) +
        (57  << uint8(MessageType.RequestCallback) * 8) +
        (41  << uint8(MessageType.SetRequestManager) * 8) +
        (89  << uint8(MessageType.ManagerCallFromSpoke) * 8) +
        (43  << uint8(MessageType.UpdateManager) * 8) +
        (57  << uint8(MessageType.ManagerCallFromHub) * 8) +
        (41  << uint8(MessageType.SetPolicy) * 8) +
        (9   << uint8(MessageType.AuthorizeSpokeCall) * 8) +
        (9   << uint8(MessageType.UnauthorizeSpokeCall) * 8);

    function messageType(bytes memory message) internal pure returns (MessageType) {
        return MessageType(message.toUint8(0));
    }

    function messageCode(bytes memory message) internal pure returns (uint8) {
        return message.toUint8(0);
    }

    function messageLength(bytes memory message) internal pure returns (uint16 length) {
        uint8 kind = message.toUint8(0);
        require(kind != uint8(MessageType._Invalid) && kind <= uint8(type(MessageType).max), UnknownMessageType());

        length = uint16(uint8(bytes32(MESSAGE_LENGTHS_1)[31 - kind]));

        // NotifyShareClass carries a fixed 16-byte extraGasLimit suffix but its base length (250) leaves no
        // room for it within the single-byte table slot, so add it here. NotifyShareMetadata is kept uniform.
        if (kind == uint8(MessageType.NotifyShareClass) || kind == uint8(MessageType.NotifyShareMetadata)) {
            length += 16;
        }

        // Special treatment for messages with dynamic size:
        if (kind == uint8(MessageType.NotifyShareClass)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.UpdateRestriction)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.UpdateVault)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.ManagerCallFromHub)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.ManagerCallFromSpoke)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.Request)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.RequestCallback)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.AuthorizeSpokeCall)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.UnauthorizeSpokeCall)) {
            length += 2 + message.toUint16(length); //payloadLength
        } else if (kind == uint8(MessageType.SetPoolAdapters)) {
            length += message.toUint16(12) * 32; // message with variable length
        }
    }

    function messagePoolId(bytes memory message) internal pure returns (PoolId poolId) {
        uint8 kind = message.toUint8(0);

        // SetPoolAdapters is pool-independent in framing but configures a specific pool's adapter set,
        // and carries its PoolId in position 1. Reporting that PoolId lets the update route over the
        // pool's own adapters instead of the global set (MultiAdapter falls back to global while the
        // pool has no set yet, so initialization still works). All messages from NotifyPool onward
        // likewise carry a PoolId in position 1.
        if (kind == uint8(MessageType.SetPoolAdapters) || kind >= uint8(MessageType.NotifyPool)) {
            return PoolId.wrap(message.toUint64(1));
        }

        return PoolId.wrap(0);
    }

    /// @notice Returns the centrifugeId that `message` must originate from, or 0 if any source is permitted.
    ///
    ///         When adding a new message type, classify it here. A spoke->hub message MUST be added to
    ///         the exclusion list (or handled explicitly), otherwise it will be incorrectly rejected when
    ///         arriving from its source chain. This function is exhaustively checked in MessageLib.t.sol.
    function messageSourceCentrifugeId(bytes memory message) internal pure returns (uint16) {
        MessageType kind = MessageType(message.toUint8(0));

        // Hub->spoke: SetPoolAdapters and all messages from NotifyPool upward, except the spoke->hub
        // exclusions below. All hub->spoke messages carry their poolId at offset 1 (big-endian uint64).
        // Request and UpdateAssets are excluded here and handled by the asset-homed branch below.
        if (
            kind == MessageType.SetPoolAdapters
                || (kind >= MessageType.NotifyPool
                    && kind != MessageType.InitiateTransferShares
                    && kind != MessageType.UpdateAssets
                    && kind != MessageType.UpdateShares
                    && kind != MessageType.Request
                    && kind != MessageType.ManagerCallFromSpoke)
        ) {
            uint16 hub = messagePoolId(message).centrifugeId();
            // No real pool has centrifugeId 0; reject outright rather than falling through to
            // "0 = any source".
            require(hub != 0, InvalidPoolHome());
            return hub;
        }
        if (kind == MessageType.ScheduleUpgrade || kind == MessageType.CancelUpgrade) {
            return MAINNET_CENTRIFUGE_ID;
        }
        if (kind == MessageType.RegisterAsset || kind == MessageType.Request || kind == MessageType.UpdateAssets) {
            uint16 assetHome = messageAssetId(kind, message).centrifugeId();
            // ISO-4217 currency assets (centrifugeId 0) are registered locally on the Hub and are never
            // legitimately reported by a spoke; reject outright rather than falling through to
            // "0 = any source".
            require(assetHome != 0, InvalidAssetHome());
            return assetHome;
        }
        return 0;
    }

    /// @dev The AssetId embedded in `message`. RegisterAsset carries it at offset 1; Request and
    ///      UpdateAssets carry it at offset 25 (after poolId and scId).
    function messageAssetId(MessageType kind, bytes memory message) internal pure returns (AssetId) {
        if (kind == MessageType.RegisterAsset) {
            return AssetId.wrap(message.toUint128(1));
        }
        if (kind == MessageType.Request || kind == MessageType.UpdateAssets) {
            return AssetId.wrap(message.toUint128(25));
        }
        revert UnknownMessageType();
    }

    /// @notice The pool whose adapter set should route/verify `message`. Normally the message's own pool
    ///         (`messagePoolId`), with one exception: a SetPoolAdapters for a pool that has no adapter set
    ///         yet (`poolConfigured == false`) falls back to the global pool, because the pool's first
    ///         adapter configuration has to arrive over the global set. `poolConfigured` is supplied by the
    ///         adapter layer, which is the only place that knows whether the pool already has a set.
    function routePoolId(bytes memory message, bool poolConfigured) internal pure returns (PoolId) {
        if (!poolConfigured && messageType(message) == MessageType.SetPoolAdapters) {
            return PoolId.wrap(0);
        }
        return messagePoolId(message);
    }

    function messageExtraGasLimit(bytes memory message) internal pure returns (uint128) {
        uint8 kind = message.toUint8(0);

        if (kind == uint8(MessageType.NotifyShareClass)) {
            return message.toUint128(250);
        } else if (kind == uint8(MessageType.NotifyShareMetadata)) {
            return message.toUint128(185);
        } else if (kind == uint8(MessageType.InitiateTransferShares)) {
            return message.toUint128(91);
        } else if (kind == uint8(MessageType.ExecuteTransferShares)) {
            return message.toUint128(73);
        } else if (kind == uint8(MessageType.UpdateRestriction)) {
            return message.toUint128(25);
        } else if (kind == uint8(MessageType.ManagerCallFromHub)) {
            return message.toUint128(41);
        } else if (kind == uint8(MessageType.ManagerCallFromSpoke)) {
            return message.toUint128(73);
        } else if (kind == uint8(MessageType.Request)) {
            return message.toUint128(41);
        } else if (kind == uint8(MessageType.RequestCallback)) {
            return message.toUint128(41);
        } else if (kind == uint8(MessageType.UpdateVault)) {
            return message.toUint128(74);
        } else if (kind == uint8(MessageType.UpdateAssets)) {
            return message.toUint128(75);
        } else if (kind == uint8(MessageType.UpdateShares)) {
            return message.toUint128(59);
        }

        return 0;
    }

    //---------------------------------------
    //    ScheduleUpgrade
    //---------------------------------------

    struct ScheduleUpgrade {
        bytes32 target;
    }

    function deserializeScheduleUpgrade(bytes memory data) internal pure returns (ScheduleUpgrade memory) {
        require(messageType(data) == MessageType.ScheduleUpgrade, UnknownMessageType());
        return ScheduleUpgrade({target: data.toBytes32(1)});
    }

    function serialize(ScheduleUpgrade memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.ScheduleUpgrade, t.target);
    }

    //---------------------------------------
    //    CancelUpgrade
    //---------------------------------------

    struct CancelUpgrade {
        bytes32 target;
    }

    function deserializeCancelUpgrade(bytes memory data) internal pure returns (CancelUpgrade memory) {
        require(messageType(data) == MessageType.CancelUpgrade, UnknownMessageType());
        return CancelUpgrade({target: data.toBytes32(1)});
    }

    function serialize(CancelUpgrade memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.CancelUpgrade, t.target);
    }

    //---------------------------------------
    //    RegisterAsset
    //---------------------------------------

    struct RegisterAsset {
        uint128 assetId;
        uint8 decimals;
    }

    function deserializeRegisterAsset(bytes memory data) internal pure returns (RegisterAsset memory) {
        require(messageType(data) == MessageType.RegisterAsset, UnknownMessageType());
        return RegisterAsset({assetId: data.toUint128(1), decimals: data.toUint8(17)});
    }

    function serialize(RegisterAsset memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.RegisterAsset, t.assetId, t.decimals);
    }

    //---------------------------------------
    //   SetPoolAdapters
    //---------------------------------------

    struct SetPoolAdapters {
        uint64 poolId;
        uint8 threshold;
        uint16 targetSessionId;
        bytes32[] adapterList;
    }

    function deserializeSetPoolAdapters(bytes memory data) internal pure returns (SetPoolAdapters memory) {
        require(messageType(data) == MessageType.SetPoolAdapters, UnknownMessageType());

        uint16 length = data.toUint16(12);
        bytes32[] memory adapterList = new bytes32[](length);
        for (uint256 i; i < length; i++) {
            adapterList[i] = data.toBytes32(14 + i * 32);
        }

        return SetPoolAdapters({
            poolId: data.toUint64(1),
            threshold: data.toUint8(9),
            targetSessionId: data.toUint16(10),
            adapterList: adapterList
        });
    }

    function serialize(SetPoolAdapters memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.SetPoolAdapters,
            t.poolId,
            t.threshold,
            t.targetSessionId,
            t.adapterList.length.toUint16(),
            t.adapterList
        );
    }

    //---------------------------------------
    //    NotifyPool
    //---------------------------------------

    struct NotifyPool {
        uint64 poolId;
    }

    function deserializeNotifyPool(bytes memory data) internal pure returns (NotifyPool memory) {
        require(messageType(data) == MessageType.NotifyPool, UnknownMessageType());
        return NotifyPool({poolId: data.toUint64(1)});
    }

    function serialize(NotifyPool memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.NotifyPool, t.poolId);
    }

    //---------------------------------------
    //    NotifyShareClass
    //---------------------------------------

    struct NotifyShareClass {
        uint64 poolId;
        bytes16 scId;
        string name; // Fixed to 128 bytes
        bytes32 symbol; // utf8
        uint8 decimals;
        bytes32 salt;
        bytes32 registrar;
        uint128 extraGasLimit;
        bytes payload; // Opaque, forwarded to the registrar on token creation
    }

    function deserializeNotifyShareClass(bytes memory data) internal pure returns (NotifyShareClass memory) {
        require(messageType(data) == MessageType.NotifyShareClass, UnknownMessageType());
        uint16 payloadLength = data.toUint16(266);
        return NotifyShareClass({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            name: data.slice(25, 128).bytes128ToString(),
            symbol: data.toBytes32(153),
            decimals: data.toUint8(185),
            salt: data.toBytes32(186),
            registrar: data.toBytes32(218),
            extraGasLimit: data.toUint128(250),
            payload: data.slice(268, payloadLength)
        });
    }

    function serialize(NotifyShareClass memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.NotifyShareClass,
            t.poolId,
            t.scId,
            bytes(t.name).sliceZeroPadded(0, 128),
            t.symbol,
            t.decimals,
            t.salt,
            t.registrar,
            t.extraGasLimit,
            t.payload.length.toUint16(),
            t.payload
        );
    }

    //---------------------------------------
    //    NotifyPricePoolPerShare
    //---------------------------------------

    struct NotifyPricePoolPerShare {
        uint64 poolId;
        bytes16 scId;
        uint128 price;
        uint64 timestamp;
    }

    function deserializeNotifyPricePoolPerShare(bytes memory data)
        internal
        pure
        returns (NotifyPricePoolPerShare memory)
    {
        require(messageType(data) == MessageType.NotifyPricePoolPerShare, UnknownMessageType());
        return NotifyPricePoolPerShare({
            poolId: data.toUint64(1), scId: data.toBytes16(9), price: data.toUint128(25), timestamp: data.toUint64(41)
        });
    }

    function serialize(NotifyPricePoolPerShare memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.NotifyPricePoolPerShare, t.poolId, t.scId, t.price, t.timestamp);
    }

    //---------------------------------------
    //    NotifyPricePoolPerAsset
    //---------------------------------------

    struct NotifyPricePoolPerAsset {
        uint64 poolId;
        bytes16 scId;
        uint128 assetId;
        uint128 price;
        uint64 timestamp;
    }

    function deserializeNotifyPricePoolPerAsset(bytes memory data)
        internal
        pure
        returns (NotifyPricePoolPerAsset memory)
    {
        require(messageType(data) == MessageType.NotifyPricePoolPerAsset, UnknownMessageType());
        return NotifyPricePoolPerAsset({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            assetId: data.toUint128(25),
            price: data.toUint128(41),
            timestamp: data.toUint64(57)
        });
    }

    function serialize(NotifyPricePoolPerAsset memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.NotifyPricePoolPerAsset, t.poolId, t.scId, t.assetId, t.price, t.timestamp);
    }

    //---------------------------------------
    //    NotifyShareMetadata
    //---------------------------------------

    struct NotifyShareMetadata {
        uint64 poolId;
        bytes16 scId;
        string name; // Fixed to 128 bytes
        bytes32 symbol; // utf8
        uint128 extraGasLimit;
    }

    function deserializeNotifyShareMetadata(bytes memory data) internal pure returns (NotifyShareMetadata memory) {
        require(messageType(data) == MessageType.NotifyShareMetadata, UnknownMessageType());
        return NotifyShareMetadata({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            name: data.slice(25, 128).bytes128ToString(),
            symbol: data.toBytes32(153),
            extraGasLimit: data.toUint128(185)
        });
    }

    function serialize(NotifyShareMetadata memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.NotifyShareMetadata,
            t.poolId,
            t.scId,
            bytes(t.name).sliceZeroPadded(0, 128),
            t.symbol,
            t.extraGasLimit
        );
    }

    //---------------------------------------
    //    InitiateTransferShares
    //---------------------------------------

    struct InitiateTransferShares {
        uint64 poolId;
        bytes16 scId;
        uint16 centrifugeId;
        bytes32 receiver;
        uint128 amount;
        uint128 remoteExtraGasLimit;
        uint128 extraGasLimit;
        // The originator of the transfer (the real sender), forwarded to the Hub-side bridging hook.
        bytes32 sender;
    }

    function deserializeInitiateTransferShares(bytes memory data)
        internal
        pure
        returns (InitiateTransferShares memory)
    {
        require(messageType(data) == MessageType.InitiateTransferShares, UnknownMessageType());
        return InitiateTransferShares({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            centrifugeId: data.toUint16(25),
            receiver: data.toBytes32(27),
            amount: data.toUint128(59),
            remoteExtraGasLimit: data.toUint128(75),
            extraGasLimit: data.toUint128(91),
            sender: data.toBytes32(107)
        });
    }

    function serialize(InitiateTransferShares memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.InitiateTransferShares,
            t.poolId,
            t.scId,
            t.centrifugeId,
            t.receiver,
            t.amount,
            t.remoteExtraGasLimit,
            t.extraGasLimit,
            t.sender
        );
    }

    //---------------------------------------
    //    ExecuteTransferShares
    //---------------------------------------

    struct ExecuteTransferShares {
        uint64 poolId;
        bytes16 scId;
        bytes32 receiver;
        uint128 amount;
        uint128 extraGasLimit;
    }

    function deserializeExecuteTransferShares(bytes memory data) internal pure returns (ExecuteTransferShares memory) {
        require(messageType(data) == MessageType.ExecuteTransferShares, UnknownMessageType());
        return ExecuteTransferShares({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            receiver: data.toBytes32(25),
            amount: data.toUint128(57),
            extraGasLimit: data.toUint128(73)
        });
    }

    function serialize(ExecuteTransferShares memory t) internal pure returns (bytes memory) {
        return
            abi.encodePacked(MessageType.ExecuteTransferShares, t.poolId, t.scId, t.receiver, t.amount, t.extraGasLimit);
    }

    //---------------------------------------
    //    UpdateRestriction
    //---------------------------------------

    struct UpdateRestriction {
        uint64 poolId;
        bytes16 scId;
        uint128 extraGasLimit;
        bytes payload; // As sequence of bytes
    }

    function deserializeUpdateRestriction(bytes memory data) internal pure returns (UpdateRestriction memory) {
        require(messageType(data) == MessageType.UpdateRestriction, UnknownMessageType());

        uint16 payloadLength = data.toUint16(41);
        return UpdateRestriction({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            extraGasLimit: data.toUint128(25),
            payload: data.slice(43, payloadLength)
        });
    }

    function serialize(UpdateRestriction memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.UpdateRestriction, t.poolId, t.scId, t.extraGasLimit, t.payload.length.toUint16(), t.payload
        );
    }

    //---------------------------------------
    //    ManagerCallFromHub
    //---------------------------------------

    /// @dev Generic hub->target manager call routed through the Envoy on the receiving chain. Pool-scoped;
    ///      any `scId` is encoded inside `payload` by the caller.
    struct ManagerCallFromHub {
        uint64 poolId;
        bytes32 target;
        uint128 extraGasLimit;
        bytes payload; // As sequence of bytes
    }

    function deserializeManagerCallFromHub(bytes memory data) internal pure returns (ManagerCallFromHub memory) {
        require(messageType(data) == MessageType.ManagerCallFromHub, UnknownMessageType());
        uint16 payloadLength = data.toUint16(57);
        return ManagerCallFromHub({
            poolId: data.toUint64(1),
            target: data.toBytes32(9),
            extraGasLimit: data.toUint128(41),
            payload: data.slice(59, payloadLength)
        });
    }

    function serialize(ManagerCallFromHub memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.ManagerCallFromHub, t.poolId, t.target, t.extraGasLimit, t.payload.length.toUint16(), t.payload
        );
    }

    //---------------------------------------
    //    ManagerCallFromSpoke
    //---------------------------------------

    struct ManagerCallFromSpoke {
        uint64 poolId;
        bytes32 target;
        bytes32 sender;
        uint128 extraGasLimit;
        bytes payload; // As sequence of bytes
    }

    function deserializeManagerCallFromSpoke(bytes memory data) internal pure returns (ManagerCallFromSpoke memory) {
        require(messageType(data) == MessageType.ManagerCallFromSpoke, UnknownMessageType());
        uint16 payloadLength = data.toUint16(89);
        return ManagerCallFromSpoke({
            poolId: data.toUint64(1),
            target: data.toBytes32(9),
            sender: data.toBytes32(41),
            extraGasLimit: data.toUint128(73),
            payload: data.slice(91, payloadLength)
        });
    }

    function serialize(ManagerCallFromSpoke memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.ManagerCallFromSpoke,
            t.poolId,
            t.target,
            t.sender,
            t.extraGasLimit,
            t.payload.length.toUint16(),
            t.payload
        );
    }

    //---------------------------------------
    //    Request
    //---------------------------------------

    struct Request {
        uint64 poolId;
        bytes16 scId;
        uint128 assetId;
        uint128 extraGasLimit;
        bytes payload; // As sequence of bytes
    }

    function deserializeRequest(bytes memory data) internal pure returns (Request memory) {
        require(messageType(data) == MessageType.Request, UnknownMessageType());
        uint16 payloadLength = data.toUint16(57);
        return Request({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            assetId: data.toUint128(25),
            extraGasLimit: data.toUint128(41),
            payload: data.slice(59, payloadLength)
        });
    }

    function serialize(Request memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.Request, t.poolId, t.scId, t.assetId, t.extraGasLimit, t.payload.length.toUint16(), t.payload
        );
    }

    //---------------------------------------
    //    RequestCallback
    //---------------------------------------

    struct RequestCallback {
        uint64 poolId;
        bytes16 scId;
        uint128 assetId;
        uint128 extraGasLimit;
        bytes payload; // As sequence of bytes
    }

    function deserializeRequestCallback(bytes memory data) internal pure returns (RequestCallback memory) {
        require(messageType(data) == MessageType.RequestCallback, UnknownMessageType());
        uint16 payloadLength = data.toUint16(57);
        return RequestCallback({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            assetId: data.toUint128(25),
            extraGasLimit: data.toUint128(41),
            payload: data.slice(59, payloadLength)
        });
    }

    function serialize(RequestCallback memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.RequestCallback,
            t.poolId,
            t.scId,
            t.assetId,
            t.extraGasLimit,
            t.payload.length.toUint16(),
            t.payload
        );
    }

    //---------------------------------------
    //   VaultUpdate
    //---------------------------------------

    struct UpdateVault {
        uint64 poolId;
        bytes16 scId;
        uint128 assetId;
        bytes32 vaultOrFactory;
        uint8 kind; // VaultUpdateKind
        uint128 extraGasLimit;
        bytes payload; // Opaque, forwarded to the factory on DeployAndLink
    }

    function deserializeUpdateVault(bytes memory data) internal pure returns (UpdateVault memory) {
        require(messageType(data) == MessageType.UpdateVault, UnknownMessageType());
        uint16 payloadLength = data.toUint16(90);
        return UpdateVault({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            assetId: data.toUint128(25),
            vaultOrFactory: data.toBytes32(41),
            kind: data.toUint8(73),
            extraGasLimit: data.toUint128(74),
            payload: data.slice(92, payloadLength)
        });
    }

    function serialize(UpdateVault memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.UpdateVault,
            t.poolId,
            t.scId,
            t.assetId,
            t.vaultOrFactory,
            t.kind,
            t.extraGasLimit,
            t.payload.length.toUint16(),
            t.payload
        );
    }

    //---------------------------------------
    //   SetRequestManager
    //---------------------------------------

    struct SetRequestManager {
        uint64 poolId;
        bytes32 manager;
    }

    function deserializeSetRequestManager(bytes memory data) internal pure returns (SetRequestManager memory) {
        require(messageType(data) == MessageType.SetRequestManager, UnknownMessageType());
        return SetRequestManager({poolId: data.toUint64(1), manager: data.toBytes32(9)});
    }

    function serialize(SetRequestManager memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.SetRequestManager, t.poolId, t.manager);
    }

    //---------------------------------------
    //    UpdateAssets
    //---------------------------------------

    struct UpdateAssets {
        uint64 poolId;
        bytes16 scId;
        uint128 assetId;
        uint128 amount;
        uint64 timestamp;
        bool isIncrease;
        bool isSnapshot;
        uint64 nonce;
        uint128 extraGasLimit;
    }

    function deserializeUpdateAssets(bytes memory data) internal pure returns (UpdateAssets memory h) {
        require(messageType(data) == MessageType.UpdateAssets, UnknownMessageType());

        return UpdateAssets({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            assetId: data.toUint128(25),
            amount: data.toUint128(41),
            timestamp: data.toUint64(57),
            isIncrease: data.toBool(65),
            isSnapshot: data.toBool(66),
            nonce: data.toUint64(67),
            extraGasLimit: data.toUint128(75)
        });
    }

    function serialize(UpdateAssets memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.UpdateAssets,
            t.poolId,
            t.scId,
            t.assetId,
            t.amount,
            t.timestamp,
            t.isIncrease,
            t.isSnapshot,
            t.nonce,
            t.extraGasLimit
        );
    }

    //---------------------------------------
    //    UpdateShares
    //---------------------------------------

    struct UpdateShares {
        uint64 poolId;
        bytes16 scId;
        uint128 shares;
        uint64 timestamp;
        bool isIssuance;
        bool isSnapshot;
        uint64 nonce;
        uint128 extraGasLimit;
    }

    function deserializeUpdateShares(bytes memory data) internal pure returns (UpdateShares memory) {
        require(messageType(data) == MessageType.UpdateShares, UnknownMessageType());

        return UpdateShares({
            poolId: data.toUint64(1),
            scId: data.toBytes16(9),
            shares: data.toUint128(25),
            timestamp: data.toUint64(41),
            isIssuance: data.toBool(49),
            isSnapshot: data.toBool(50),
            nonce: data.toUint64(51),
            extraGasLimit: data.toUint128(59)
        });
    }

    function serialize(UpdateShares memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(
            MessageType.UpdateShares,
            t.poolId,
            t.scId,
            t.shares,
            t.timestamp,
            t.isIssuance,
            t.isSnapshot,
            t.nonce,
            t.extraGasLimit
        );
    }

    //---------------------------------------
    //   UpdateManager
    //---------------------------------------

    struct UpdateManager {
        uint64 poolId;
        uint8 kind;
        bytes32 who;
        bool canManage;
    }

    function deserializeUpdateManager(bytes memory data) internal pure returns (UpdateManager memory) {
        require(messageType(data) == MessageType.UpdateManager, UnknownMessageType());
        return UpdateManager({
            poolId: data.toUint64(1), kind: data.toUint8(9), who: data.toBytes32(10), canManage: data.toBool(42)
        });
    }

    function serialize(UpdateManager memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.UpdateManager, t.poolId, t.kind, t.who, t.canManage);
    }

    //---------------------------------------
    //   SetPolicy
    //---------------------------------------

    struct SetPolicy {
        uint64 poolId;
        bytes32 policy;
    }

    function deserializeSetPolicy(bytes memory data) internal pure returns (SetPolicy memory) {
        require(messageType(data) == MessageType.SetPolicy, UnknownMessageType());
        return SetPolicy({poolId: data.toUint64(1), policy: data.toBytes32(9)});
    }

    function serialize(SetPolicy memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.SetPolicy, t.poolId, t.policy);
    }

    //---------------------------------------
    //   AuthorizeSpokeCall
    //---------------------------------------

    struct AuthorizeSpokeCall {
        uint64 poolId;
        bytes payload; // The exact spoke calldata being authorized
    }

    function deserializeAuthorizeSpokeCall(bytes memory data) internal pure returns (AuthorizeSpokeCall memory) {
        require(messageType(data) == MessageType.AuthorizeSpokeCall, UnknownMessageType());

        uint16 payloadLength = data.toUint16(9);
        return AuthorizeSpokeCall({poolId: data.toUint64(1), payload: data.slice(11, payloadLength)});
    }

    function serialize(AuthorizeSpokeCall memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.AuthorizeSpokeCall, t.poolId, t.payload.length.toUint16(), t.payload);
    }

    //---------------------------------------
    //   UnauthorizeSpokeCall
    //---------------------------------------

    struct UnauthorizeSpokeCall {
        uint64 poolId;
        bytes payload; // The exact spoke calldata whose authorization is being revoked
    }

    function deserializeUnauthorizeSpokeCall(bytes memory data) internal pure returns (UnauthorizeSpokeCall memory) {
        require(messageType(data) == MessageType.UnauthorizeSpokeCall, UnknownMessageType());

        uint16 payloadLength = data.toUint16(9);
        return UnauthorizeSpokeCall({poolId: data.toUint64(1), payload: data.slice(11, payloadLength)});
    }

    function serialize(UnauthorizeSpokeCall memory t) internal pure returns (bytes memory) {
        return abi.encodePacked(MessageType.UnauthorizeSpokeCall, t.poolId, t.payload.length.toUint16(), t.payload);
    }
}
