// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import {ICreateX} from "./utils/ICreateX.sol";
import {CREATEX_ADDRESS} from "./utils/CreateX.d.sol";
import {CreateXScript} from "./utils/CreateXScript.sol";
import {JsonRegistry} from "./utils/JsonRegistry.s.sol";

import "forge-std/Script.sol";

contract BaseDeployer is Script, JsonRegistry, CreateXScript {
    string internal suffix;
    address public deployer;

    function _init(string memory suffix_, address deployer_) internal {
        setUpCreateXFactory();

        suffix = suffix_;
        deployer = deployer_;
    }

    function _isLegacyVersion(string memory version) private pure returns (bool) {
        return keccak256(abi.encodePacked(version)) == keccak256(abi.encodePacked("3"));
    }

    function _makeSalt(string memory contractName, string memory version) private view returns (bytes32) {
        require(deployer != address(0), "BaseDeployer::_init() must be called!");

        // Legacy contracts had a different salt computation (i.e: root in some chains)
        if (_isLegacyVersion(version)) {
            return keccak256(abi.encodePacked(contractName, keccak256(abi.encodePacked(version))));
        }

        bytes memory compoundedVersion = bytes(string.concat(version, "-", suffix));
        require(compoundedVersion.length <= 32, "Version + suffix is too large");

        bytes32 versionHash = bytes(suffix).length > 0 ? bytes32(compoundedVersion) : bytes32(bytes(version));
        bytes32 baseHash = keccak256(abi.encodePacked(contractName, versionHash));

        // NOTE: To avoid CreateX InvalidSalt issues, 21st byte needs to be 0
        return bytes32(abi.encodePacked(bytes20(deployer), bytes1(0x0), bytes11(baseHash)));
    }

    /// @dev Generates a deterministic salt and registers the predicted address.
    ///      The version must match the one used at initial deployment to reuse existing addresses.
    ///      Use the suffix (instead of changing the version) to create isolated fresh deployments.
    function createSalt(string memory contractName, string memory contractVersion) internal returns (bytes32) {
        bytes32 salt = _makeSalt(contractName, contractVersion);

        register(contractName, previewCreate3Address(contractName, contractVersion), contractVersion);

        return salt;
    }

    /// @dev Previews the address generated by create3(createSalt(contractName, contractVersion))
    function previewCreate3Address(string memory contractName, string memory contractVersion)
        internal
        view
        returns (address)
    {
        bytes32 salt = _makeSalt(contractName, contractVersion);

        // Legacy salts don't embed the deployer address, so CreateX guards them with keccak256(salt).
        return _isLegacyVersion(contractVersion)
            ? ICreateX(CREATEX_ADDRESS).computeCreate3Address(keccak256(abi.encodePacked(salt)), CREATEX_ADDRESS)
            : computeCreate3Address(salt, deployer);
    }
}
