@startuml
hide empty members

package spoke {
    interface IVaultManager
}

interface IBaseRequestManager

interface IDepositManager
interface IRedeemManager

interface IAsyncDepositManager
interface ISyncManager
interface IAsyncRedeemManager

interface IAsyncVaultManager
interface ISyncManager

IBaseRequestManager -up-|> IVaultManager
IDepositManager -up-|> IBaseRequestManager
IRedeemManager -up-|> IBaseRequestManager

IAsyncDepositManager -up-|> IDepositManager
ISyncManager -up-|> IDepositManager
IAsyncRedeemManager -up-|> IRedeemManager

IAsyncVaultManager -up-|> IAsyncDepositManager
IAsyncVaultManager -up-|> IAsyncRedeemManager

ISyncManager -up-|> ISyncManager

abstract BaseRequestManager
class AsyncVaultManager
class SyncManager

AsyncVaultManager -up-|> BaseRequestManager
SyncManager -up-|> BaseRequestManager

BaseRequestManager -up-|> IBaseRequestManager
AsyncVaultManager -up-|> IAsyncVaultManager
SyncManager -up-|> ISyncManager

@enduml
