@startuml
hide empty members

package misc {
    interface Escrow
}

package spoke {
    class Spoke
    class BalanceSheet
    interface IUpdateContract
    interface IVaultManager
    interface IRequestManager
}

interface IBaseRequestManager

interface IAsyncRequestManager
interface ISyncManager

class GlobalEscrow
class VaultEscrow

IBaseRequestManager -up-|> IRequestManager
IBaseRequestManager -up-|> IVaultManager

IAsyncRequestManager -up-|> IBaseRequestManager
ISyncManager -up-|> IUpdateContract

GlobalEscrow -up-|> Escrow
VaultEscrow -up-|> Escrow

AsyncRequestManager -up--> GlobalEscrow
AsyncRequestManager -up--> BalanceSheet
AsyncRequestManager -up-|> IAsyncRequestManager

SyncManager -up-|> ISyncManager
SyncManager -up--> BalanceSheet

VaultRouter -up-> VaultEscrow
VaultRouter -up-> Spoke

@enduml
