@startuml spoke-managers
title Spoke Managers
hide empty members

package core {
    interface ISpoke
    interface ISnapshotQueue
}

OnOfframpManager --> ISpoke
QueueManager --> ISpoke
QueueManager --> ISnapshotQueue

note top of OnOfframpManager
  Manages on/off-ramping
  for assets entering/exiting
  the protocol
end note

note top of QueueManager
  Manages submission of queued
  assets and shares
end note

@enduml
