name: "Anvil Deploy Tests"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
    anvil-deploy:
        runs-on: ubuntu-latest
        permissions:
          contents: 'read'
          id-token: 'write'        
        steps:
        - uses: actions/checkout@v3
        - id: 'auth'
          uses: 'google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f' # v2.1.7
          with:
            workload_identity_provider: ${{ secrets.GCP_WIP }}
            service_account: ${{ secrets.GCP_SA }}
            create_credentials_file: true
            cleanup_credentials: true
  
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a' # v2.1.2
          with:
            version: '>= 363.0.0'
        - name: Install Foundry
          uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # 1.4.0
          with:
            version: 1.2.3            
        #Make sure all tools are installed and with proper versions
        - name: Setup deployer tools
          env:
            CI_MODE: true
          run: |
            script/deploy/setup.sh
        - name: Deploy Anvil
          run: |
            python3 script/deploy/deploy.py --network anvil 