name: "Fork Tests"

on:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  fork-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deployer-setup
        with:
          gcp-workload-identity-provider: ${{ secrets.GCP_WIP }}
          gcp-service-account: ${{ secrets.GCP_SA }}
      - name: Run fork and spell tests
        run: forge test --match-path "test/integration/{fork,spell}/**/*.sol" -vv
        env:
          FOUNDRY_PROFILE: ci
